package ludo.game;

public enum GameEvent {
    GAME_START,
    FIRST_PLAYER_CHOSEN,
    DICE_ROLLED,
    PIECE_MOVED_TO_START,
    PIECE_MOVED,
    PIECE_BLOCKED,
    PIECE_CAPTURED,
    MYSTERY_CELL_SPAWNED,
    MYSTERY_CELL_TELEPORT,
    PIECE_ENERGIZED,
    PIECE_SICK,
    PIECE_BRIEFING,
    PIECE_BRIEFING_TELEPORT,
    PIECE_DIRECTION_CHANGED,
    ROUND_STATUS,
    PLAYER_WINS
}
